import type { Producer, Product, Story } from "./types";
import { EMPTY_SOCIAL_FIELDS } from "./social";

export const SEED_PRODUCERS: Producer[] = [
  {
    id: "nelu",
    name: "Grădina lui Nelu",
    village: "Săcueni",
    county: "Bihor",
    blurb: "Roșii de inimă, ardei și vinete de pe aracii din curte. Nelu culege dimineața.",
    rating: 4.9,
    ratingCount: 87,
    km: 2.1,
    pickup: true,
    delivery: true,
    deliveryFeeBani: 800,
    freeOverBani: 4000,
    minOrderBani: 0,
    phone: "0744 100 201",
    image: "/images/gradina-nelu.jpg",
    avatar: "/images/rosii.jpg",
    socialIntro: "Urmărește grădina — ce culegem azi, rețete și taraba de la poartă.",
    facebook: "https://www.facebook.com/gradinaluinelu",
    instagram: "https://www.instagram.com/gradinaluinelu",
    youtube: "https://www.youtube.com/@gradinaluinelu",
    tiktok: "",
    website: "",
    active: true,
    blocked: false,
    warningCount: 0,
  },
  {
    id: "mama",
    name: "Legume de la Mama",
    village: "Vultureni",
    county: "Cluj",
    blurb: "Cartofi, ouă, pâine și borcane ca la țară. Ioana pune pe masă ce are în grădină.",
    rating: 4.8,
    ratingCount: 64,
    km: 3.4,
    pickup: true,
    delivery: true,
    deliveryFeeBani: 1000,
    freeOverBani: 5000,
    minOrderBani: 2500,
    phone: "0745 200 302",
    image: "/images/mama.jpg",
    avatar: "/images/paine.jpg",
    ...EMPTY_SOCIAL_FIELDS,
    active: true,
    blocked: false,
    warningCount: 0,
  },
  {
    id: "marin",
    name: "Ferma Dâmbovița",
    village: "Găești",
    county: "Dâmbovița",
    blurb: "Caș afumat pe fag, telemea de oaie, cașcaval. Marin ține ferma lângă Găești.",
    rating: 4.7,
    ratingCount: 53,
    km: 4.8,
    pickup: true,
    delivery: true,
    deliveryFeeBani: 1200,
    freeOverBani: 8000,
    minOrderBani: 2500,
    phone: "0722 300 403",
    image: "/images/ferma.jpg",
    avatar: "/images/cascaval.jpg",
    ...EMPTY_SOCIAL_FIELDS,
    active: true,
    blocked: false,
    warningCount: 0,
  },
  {
    id: "moise",
    name: "Livada Moise",
    village: "Odobești",
    county: "Vrancea",
    blurb: "Livada bătrână de pe deal. Mere, prune, piersici, culese cu mâna.",
    rating: 4.8,
    ratingCount: 41,
    km: 6.2,
    pickup: true,
    delivery: false,
    deliveryFeeBani: 0,
    freeOverBani: 0,
    minOrderBani: 0,
    phone: "0733 400 504",
    image: "/images/livada.jpg",
    avatar: "/images/mere.jpg",
    ...EMPTY_SOCIAL_FIELDS,
    active: true,
    blocked: false,
    warningCount: 0,
  },
  {
    id: "vasile",
    name: "Stupina Vasile",
    village: "Fetești",
    county: "Ialomița",
    blurb: "Miere de tei, mutată după înflorire, nepasteurizată. Polen și sirop de soc.",
    rating: 4.9,
    ratingCount: 38,
    km: 7.5,
    pickup: true,
    delivery: true,
    deliveryFeeBani: 900,
    freeOverBani: 4500,
    minOrderBani: 0,
    phone: "0766 500 605",
    image: "/images/stupina.jpg",
    avatar: "/images/miere.jpg",
    ...EMPTY_SOCIAL_FIELDS,
    active: true,
    blocked: false,
    warningCount: 0,
  },
];

export const SEED_PRODUCTS: Product[] = [
  { id: "rosii", slug: "rosii-de-inima", name: "Roșii de inimă", category: "legume", producerId: "nelu", unit: "kg", priceBani: 1250, bulkQty: 5, bulkPriceBani: 1100, step: 0.5, stock: 18, image: "/images/rosii.jpg", blurb: "Nelu le culege când crapă ușor la umăr.", visible: true, featured: true, sortOrder: 1 },
  { id: "ardei", slug: "ardei-capia", name: "Ardei capia", category: "legume", producerId: "nelu", unit: "kg", priceBani: 900, bulkQty: null, bulkPriceBani: null, step: 0.5, stock: 12, image: "/images/ardei.jpg", blurb: "Dulci, pentru cuptor sau zacuscă.", visible: true, featured: false, sortOrder: 2 },
  { id: "vinete", slug: "vinete", name: "Vinete", category: "legume", producerId: "nelu", unit: "kg", priceBani: 700, bulkQty: null, bulkPriceBani: null, step: 0.5, stock: 10, image: "/images/vinete.jpg", blurb: "Lucioase, pentru salată de vinete.", visible: true, featured: false, sortOrder: 3 },
  { id: "capsuni", slug: "capsuni", name: "Căpșuni", category: "fructe", producerId: "nelu", unit: "kg", priceBani: 1800, bulkQty: null, bulkPriceBani: null, step: 0.5, stock: 6, image: "/images/capsuni.jpg", blurb: "De pe rândurile de lângă șură, culese azi.", visible: true, featured: true, sortOrder: 4 },
  { id: "morcovi", slug: "morcovi", name: "Morcovi", category: "legume", producerId: "mama", unit: "kg", priceBani: 420, bulkQty: 5, bulkPriceBani: 360, step: 0.5, stock: 30, image: "/images/morcovi.jpg", blurb: "Cu verdeață, spălați în curte.", visible: true, featured: false, sortOrder: 5 },
  { id: "castraveti", slug: "castraveti", name: "Castraveți", category: "legume", producerId: "mama", unit: "kg", priceBani: 500, bulkQty: null, bulkPriceBani: null, step: 0.5, stock: 16, image: "/images/castraveti.jpg", blurb: "Crocanți, pentru salată sau murături.", visible: true, featured: false, sortOrder: 6 },
  { id: "cartofi", slug: "cartofi-rosii", name: "Cartofi roșii", category: "cartofi-ceapa", producerId: "mama", unit: "kg", priceBani: 380, bulkQty: 5, bulkPriceBani: 320, step: 1, stock: 80, image: "/images/cartofi.jpg", blurb: "De toamnă, buni la cuptor.", visible: true, featured: true, sortOrder: 7 },
  { id: "ceapa", slug: "ceapa", name: "Ceapă", category: "cartofi-ceapa", producerId: "mama", unit: "kg", priceBani: 350, bulkQty: 5, bulkPriceBani: 300, step: 0.5, stock: 40, image: "/images/ceapa.jpg", blurb: "Uscată la soare, ține peste iarnă.", visible: true, featured: false, sortOrder: 8 },
  { id: "oua", slug: "oua-de-tara", name: "Ouă de țară", category: "carne-oua", producerId: "mama", unit: "cutie", priceBani: 1600, bulkQty: null, bulkPriceBani: null, step: 1, stock: 24, image: "/images/oua.jpg", blurb: "Cutie de 10. Găinile umblă prin curte.", visible: true, featured: true, sortOrder: 9 },
  { id: "paine", slug: "paine-de-casa", name: "Pâine de casă", category: "panificatie", producerId: "mama", unit: "buc", priceBani: 1200, bulkQty: 3, bulkPriceBani: 1100, step: 1, stock: 14, image: "/images/paine.jpg", blurb: "Frământată dimineața, coaptă în cuptor.", visible: true, featured: false, sortOrder: 10 },
  { id: "placinta", slug: "placinta-cu-branza", name: "Plăcintă cu brânză", category: "panificatie", producerId: "mama", unit: "buc", priceBani: 2200, bulkQty: null, bulkPriceBani: null, step: 1, stock: 8, image: "/images/placinta.jpg", blurb: "Foaie subțire, brânză de vaci din sat.", visible: true, featured: false, sortOrder: 11 },
  { id: "zacusca", slug: "zacusca-de-casa", name: "Zacuscă de casă", category: "muraturi", producerId: "mama", unit: "borcan", priceBani: 1800, bulkQty: 3, bulkPriceBani: 1600, step: 1, stock: 20, image: "/images/zacusca.jpg", blurb: "Ardei și vinete, fierte în ceaun.", visible: true, featured: false, sortOrder: 12 },
  { id: "murati", slug: "castraveti-murati", name: "Castraveți murați", category: "muraturi", producerId: "mama", unit: "borcan", priceBani: 1400, bulkQty: null, bulkPriceBani: null, step: 1, stock: 15, image: "/images/zacusca.jpg", blurb: "În saramură, cu mărar și hrean.", visible: true, featured: false, sortOrder: 13 },
  { id: "cas", slug: "cas-afumat", name: "Caș afumat", category: "lactate", producerId: "marin", unit: "kg", priceBani: 3500, bulkQty: null, bulkPriceBani: null, step: 0.2, stock: 6, image: "/images/cas-afumat.jpg", blurb: "Afumat pe fag, de la ferma de lângă Găești.", visible: true, featured: true, sortOrder: 14 },
  { id: "cascaval", slug: "cascaval-de-vaca", name: "Cașcaval de vacă", category: "lactate", producerId: "marin", unit: "kg", priceBani: 4200, bulkQty: null, bulkPriceBani: null, step: 0.2, stock: 5, image: "/images/cascaval.jpg", blurb: "Maturat în pivniță, se taie la cântar.", visible: true, featured: false, sortOrder: 15 },
  { id: "telemea", slug: "telemea-de-oaie", name: "Telemea de oaie", category: "lactate", producerId: "marin", unit: "kg", priceBani: 3800, bulkQty: null, bulkPriceBani: null, step: 0.2, stock: 7, image: "/images/telemea.jpg", blurb: "Sărată cât trebuie, din lapte de oaie.", visible: true, featured: false, sortOrder: 16 },
  { id: "mere", slug: "mere-ionatan", name: "Mere Ionatan", category: "fructe", producerId: "moise", unit: "kg", priceBani: 650, bulkQty: 5, bulkPriceBani: 550, step: 1, stock: 50, image: "/images/mere.jpg", blurb: "Din livada bătrână, culese cu mâna.", visible: true, featured: false, sortOrder: 17 },
  { id: "prune", slug: "prune", name: "Prune", category: "fructe", producerId: "moise", unit: "kg", priceBani: 800, bulkQty: null, bulkPriceBani: null, step: 0.5, stock: 22, image: "/images/prune.jpg", blurb: "Pentru gem sau de mâncat din palmă.", visible: true, featured: false, sortOrder: 18 },
  { id: "piersici", slug: "piersici", name: "Piersici", category: "fructe", producerId: "moise", unit: "kg", priceBani: 1100, bulkQty: null, bulkPriceBani: null, step: 0.5, stock: 14, image: "/images/prune.jpg", blurb: "Coapte pe deal, miros a vară.", visible: true, featured: false, sortOrder: 19 },
  { id: "dulceata", slug: "dulceata-de-cirese", name: "Dulceață de cireșe", category: "dulceturi", producerId: "moise", unit: "borcan", priceBani: 2400, bulkQty: null, bulkPriceBani: null, step: 1, stock: 12, image: "/images/dulceata.jpg", blurb: "Fiertură scurtă, fructe întregi.", visible: true, featured: false, sortOrder: 20 },
  { id: "nuci", slug: "nuci-de-tara", name: "Nuci de țară", category: "altele", producerId: "moise", unit: "kg", priceBani: 2200, bulkQty: null, bulkPriceBani: null, step: 0.5, stock: 18, image: "/images/mere.jpg", blurb: "Uscate pe cuptor, se sparg ușor.", visible: true, featured: false, sortOrder: 21 },
  { id: "miere", slug: "miere-de-tei", name: "Miere de tei", category: "miere", producerId: "vasile", unit: "borcan", priceBani: 4500, bulkQty: 3, bulkPriceBani: 4200, step: 1, stock: 16, image: "/images/miere.jpg", blurb: "Nepasteurizată, din teiul de la Fetești.", visible: true, featured: true, sortOrder: 22 },
  { id: "polen", slug: "polen-crud", name: "Polen crud", category: "miere", producerId: "vasile", unit: "borcan", priceBani: 3200, bulkQty: null, bulkPriceBani: null, step: 1, stock: 9, image: "/images/miere.jpg", blurb: "Păstrat la rece, din sezonul de tei.", visible: true, featured: false, sortOrder: 23 },
  { id: "sirop", slug: "sirop-de-soc", name: "Sirop de soc", category: "bauturi", producerId: "vasile", unit: "sticla", priceBani: 2000, bulkQty: null, bulkPriceBani: null, step: 1, stock: 11, image: "/images/miere.jpg", blurb: "Flori culese dimineața, fierte cu lămâie.", visible: true, featured: false, sortOrder: 24 },
  { id: "ceai", slug: "ceai-de-tei", name: "Ceai de tei", category: "ceaiuri", producerId: "vasile", unit: "punga", priceBani: 1400, bulkQty: null, bulkPriceBani: null, step: 1, stock: 20, image: "/images/stupina.jpg", blurb: "Flori uscate la umbră, pungă de 50 g.", visible: true, featured: false, sortOrder: 25 },
];

export const SEED_STORIES: Story[] = [
  {
    id: "s-marin",
    slug: "povestea-lui-marin",
    producerId: "marin",
    title: "Povestea lui Marin",
    excerpt: "Cașul afumat, fumul de fag, ferma de lângă Găești.",
    body: "Marin se scoală înainte de lumină. Fumul de fag stă peste caș toată noaptea, iar dimineața tăiem rondele încă calde. Ferma e mică — câteva vaci, o turmă de oi, pivnița săpată în coastă. Cine trece pe la Găești și bate la poartă pleacă cu telemea în pânză.",
  },
  {
    id: "s-nelu",
    slug: "rosiile-de-inima-ale-lui-nelu",
    producerId: "nelu",
    title: "Roșiile de inimă ale lui Nelu",
    excerpt: "Aracii din Săcueni și roșiile care crapă la umăr.",
    body: "Nelu nu culege roșia până nu crapă puțin la umăr — atunci e dulce. Aracii sunt din alun, puși în fiecare aprilie. În iulie, grădina miroase a frunză caldă și a pământ udat seara. Le pune în lădițe, cu hârtie între rânduri, ca să ajungă întregi la tine.",
  },
  {
    id: "s-mama",
    slug: "masa-ioanei",
    producerId: "mama",
    title: "Masa Ioanei",
    excerpt: "Ouă, cartofi și verdețuri de la Vultureni.",
    body: "Ioana zice că masa trebuie să aibă culoare. Ouăle de la găinile din curte, cartofii roșii din pământul de lângă pârâu, pâinea scoasă din cuptor cât e caldă. Dacă comanzi borcan de zacuscă, ți-l pune deoparte cu etichetă scrisă de mână.",
  },
  {
    id: "s-moise",
    slug: "merele-de-pe-deal",
    producerId: "moise",
    title: "Merele de pe deal",
    excerpt: "Livada bătrână din Odobești, culeasă cu mâna, an de an.",
    body: "Moise n-a tăiat merii bătrâni. Ionatanul se ține bine peste iarnă, prunele merg la dulceață, piersicile se mănâncă în trei zile. Culege cu scara de lemn, fără scuturătoare. Dacă vrei lădiță, trebuie să treci pe la livadă — el nu umblă cu mașina în oraș.",
  },
  {
    id: "s-vasile",
    slug: "teiul-din-fetesti",
    producerId: "vasile",
    title: "Teiul din Fetești",
    excerpt: "Miere de tei, mutată după înflorire, nepasteurizată.",
    body: "Vasile mută stupii după tei. Când înflorește, satul miroase a miere de departe. Borcanele nu se încălzesc, polenul stă la rece. Un borcan de tei ține iarna întreagă, dacă nu-l termini la ceai.",
  },
];
