/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AplicatiaRouteImport } from './routes/aplicatia'
import { Route as ComandaRouteImport } from './routes/comanda'
import { Route as ContRouteImport } from './routes/cont'
import { Route as CosRouteImport } from './routes/cos'
import { Route as FavoriteRouteImport } from './routes/favorite'
import { Route as MesajeRouteImport } from './routes/mesaje'
import { Route as PovestiRouteImport } from './routes/povesti'
import { Route as ProducatoriRouteImport } from './routes/producatori'
import { Route as ProduseRouteImport } from './routes/produse'
import { Route as SetariRouteImport } from './routes/setari'
import { Route as TrimiteRouteImport } from './routes/trimite'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminComenziRouteImport } from './routes/admin.comenzi'
import { Route as AdminProducatoriRouteImport } from './routes/admin.producatori'
import { Route as AdminProduseRouteImport } from './routes/admin.produse'
import { Route as PovestiIndexRouteImport } from './routes/povesti.index'
import { Route as PovestiSlugRouteImport } from './routes/povesti.$slug'
import { Route as ProducatoriIndexRouteImport } from './routes/producatori.index'
import { Route as ProducatoriIdRouteImport } from './routes/producatori.$id'
import { Route as ProduseIndexRouteImport } from './routes/produse.index'
import { Route as ProduseSlugRouteImport } from './routes/produse.$slug'
import { Route as AdminProdusIdRouteImport } from './routes/admin.produs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicatiaRoute = AplicatiaRouteImport.update({
  id: '/aplicatia',
  path: '/aplicatia',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaRoute = ComandaRouteImport.update({
  id: '/comanda',
  path: '/comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const ContRoute = ContRouteImport.update({
  id: '/cont',
  path: '/cont',
  getParentRoute: () => rootRouteImport,
} as any)
const CosRoute = CosRouteImport.update({
  id: '/cos',
  path: '/cos',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteRoute = FavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const MesajeRoute = MesajeRouteImport.update({
  id: '/mesaje',
  path: '/mesaje',
  getParentRoute: () => rootRouteImport,
} as any)
const PovestiRoute = PovestiRouteImport.update({
  id: '/povesti',
  path: '/povesti',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducatoriRoute = ProducatoriRouteImport.update({
  id: '/producatori',
  path: '/producatori',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduseRoute = ProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => rootRouteImport,
} as any)
const SetariRoute = SetariRouteImport.update({
  id: '/setari',
  path: '/setari',
  getParentRoute: () => rootRouteImport,
} as any)
const TrimiteRoute = TrimiteRouteImport.update({
  id: '/trimite',
  path: '/trimite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComenziRoute = AdminComenziRouteImport.update({
  id: '/comenzi',
  path: '/comenzi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProducatoriRoute = AdminProducatoriRouteImport.update({
  id: '/producatori',
  path: '/producatori',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduseRoute = AdminProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => AdminRoute,
} as any)
const PovestiIndexRoute = PovestiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PovestiRoute,
} as any)
const PovestiSlugRoute = PovestiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PovestiRoute,
} as any)
const ProducatoriIndexRoute = ProducatoriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProducatoriRoute,
} as any)
const ProducatoriIdRoute = ProducatoriIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProducatoriRoute,
} as any)
const ProduseIndexRoute = ProduseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduseRoute,
} as any)
const ProduseSlugRoute = ProduseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProduseRoute,
} as any)
const AdminProdusIdRoute = AdminProdusIdRouteImport.update({
  id: '/produs/$id',
  path: '/produs/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aplicatia': typeof AplicatiaRoute
  '/comanda': typeof ComandaRoute
  '/cont': typeof ContRoute
  '/cos': typeof CosRoute
  '/favorite': typeof FavoriteRoute
  '/mesaje': typeof MesajeRoute
  '/povesti': typeof PovestiRouteWithChildren
  '/producatori': typeof ProducatoriRouteWithChildren
  '/produse': typeof ProduseRouteWithChildren
  '/setari': typeof SetariRoute
  '/trimite': typeof TrimiteRoute
  '/admin/comenzi': typeof AdminComenziRoute
  '/admin/producatori': typeof AdminProducatoriRoute
  '/admin/produse': typeof AdminProduseRoute
  '/povesti/$slug': typeof PovestiSlugRoute
  '/producatori/$id': typeof ProducatoriIdRoute
  '/produse/$slug': typeof ProduseSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/povesti/': typeof PovestiIndexRoute
  '/producatori/': typeof ProducatoriIndexRoute
  '/produse/': typeof ProduseIndexRoute
  '/admin/produs/$id': typeof AdminProdusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aplicatia': typeof AplicatiaRoute
  '/comanda': typeof ComandaRoute
  '/cont': typeof ContRoute
  '/cos': typeof CosRoute
  '/favorite': typeof FavoriteRoute
  '/mesaje': typeof MesajeRoute
  '/setari': typeof SetariRoute
  '/trimite': typeof TrimiteRoute
  '/admin/comenzi': typeof AdminComenziRoute
  '/admin/producatori': typeof AdminProducatoriRoute
  '/admin/produse': typeof AdminProduseRoute
  '/povesti/$slug': typeof PovestiSlugRoute
  '/producatori/$id': typeof ProducatoriIdRoute
  '/produse/$slug': typeof ProduseSlugRoute
  '/admin': typeof AdminIndexRoute
  '/povesti': typeof PovestiIndexRoute
  '/producatori': typeof ProducatoriIndexRoute
  '/produse': typeof ProduseIndexRoute
  '/admin/produs/$id': typeof AdminProdusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aplicatia': typeof AplicatiaRoute
  '/comanda': typeof ComandaRoute
  '/cont': typeof ContRoute
  '/cos': typeof CosRoute
  '/favorite': typeof FavoriteRoute
  '/mesaje': typeof MesajeRoute
  '/povesti': typeof PovestiRouteWithChildren
  '/producatori': typeof ProducatoriRouteWithChildren
  '/produse': typeof ProduseRouteWithChildren
  '/setari': typeof SetariRoute
  '/trimite': typeof TrimiteRoute
  '/admin/comenzi': typeof AdminComenziRoute
  '/admin/producatori': typeof AdminProducatoriRoute
  '/admin/produse': typeof AdminProduseRoute
  '/povesti/$slug': typeof PovestiSlugRoute
  '/producatori/$id': typeof ProducatoriIdRoute
  '/produse/$slug': typeof ProduseSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/povesti/': typeof PovestiIndexRoute
  '/producatori/': typeof ProducatoriIndexRoute
  '/produse/': typeof ProduseIndexRoute
  '/admin/produs/$id': typeof AdminProdusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aplicatia'
    | '/comanda'
    | '/cont'
    | '/cos'
    | '/favorite'
    | '/mesaje'
    | '/povesti'
    | '/producatori'
    | '/produse'
    | '/setari'
    | '/trimite'
    | '/admin/comenzi'
    | '/admin/producatori'
    | '/admin/produse'
    | '/povesti/$slug'
    | '/producatori/$id'
    | '/produse/$slug'
    | '/admin/'
    | '/povesti/'
    | '/producatori/'
    | '/produse/'
    | '/admin/produs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aplicatia'
    | '/comanda'
    | '/cont'
    | '/cos'
    | '/favorite'
    | '/mesaje'
    | '/setari'
    | '/trimite'
    | '/admin/comenzi'
    | '/admin/producatori'
    | '/admin/produse'
    | '/povesti/$slug'
    | '/producatori/$id'
    | '/produse/$slug'
    | '/admin'
    | '/povesti'
    | '/producatori'
    | '/produse'
    | '/admin/produs/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aplicatia'
    | '/comanda'
    | '/cont'
    | '/cos'
    | '/favorite'
    | '/mesaje'
    | '/povesti'
    | '/producatori'
    | '/produse'
    | '/setari'
    | '/trimite'
    | '/admin/comenzi'
    | '/admin/producatori'
    | '/admin/produse'
    | '/povesti/$slug'
    | '/producatori/$id'
    | '/produse/$slug'
    | '/admin/'
    | '/povesti/'
    | '/producatori/'
    | '/produse/'
    | '/admin/produs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AplicatiaRoute: typeof AplicatiaRoute
  ComandaRoute: typeof ComandaRoute
  ContRoute: typeof ContRoute
  CosRoute: typeof CosRoute
  FavoriteRoute: typeof FavoriteRoute
  MesajeRoute: typeof MesajeRoute
  PovestiRoute: typeof PovestiRouteWithChildren
  ProducatoriRoute: typeof ProducatoriRouteWithChildren
  ProduseRoute: typeof ProduseRouteWithChildren
  SetariRoute: typeof SetariRoute
  TrimiteRoute: typeof TrimiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicatia': {
      id: '/aplicatia'
      path: '/aplicatia'
      fullPath: '/aplicatia'
      preLoaderRoute: typeof AplicatiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda': {
      id: '/comanda'
      path: '/comanda'
      fullPath: '/comanda'
      preLoaderRoute: typeof ComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cont': {
      id: '/cont'
      path: '/cont'
      fullPath: '/cont'
      preLoaderRoute: typeof ContRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cos': {
      id: '/cos'
      path: '/cos'
      fullPath: '/cos'
      preLoaderRoute: typeof CosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite': {
      id: '/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof FavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesaje': {
      id: '/mesaje'
      path: '/mesaje'
      fullPath: '/mesaje'
      preLoaderRoute: typeof MesajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/povesti': {
      id: '/povesti'
      path: '/povesti'
      fullPath: '/povesti'
      preLoaderRoute: typeof PovestiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producatori': {
      id: '/producatori'
      path: '/producatori'
      fullPath: '/producatori'
      preLoaderRoute: typeof ProducatoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse': {
      id: '/produse'
      path: '/produse'
      fullPath: '/produse'
      preLoaderRoute: typeof ProduseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setari': {
      id: '/setari'
      path: '/setari'
      fullPath: '/setari'
      preLoaderRoute: typeof SetariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trimite': {
      id: '/trimite'
      path: '/trimite'
      fullPath: '/trimite'
      preLoaderRoute: typeof TrimiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comenzi': {
      id: '/admin/comenzi'
      path: '/comenzi'
      fullPath: '/admin/comenzi'
      preLoaderRoute: typeof AdminComenziRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/producatori': {
      id: '/admin/producatori'
      path: '/producatori'
      fullPath: '/admin/producatori'
      preLoaderRoute: typeof AdminProducatoriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produse': {
      id: '/admin/produse'
      path: '/produse'
      fullPath: '/admin/produse'
      preLoaderRoute: typeof AdminProduseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/povesti/': {
      id: '/povesti/'
      path: '/'
      fullPath: '/povesti/'
      preLoaderRoute: typeof PovestiIndexRouteImport
      parentRoute: typeof PovestiRoute
    }
    '/povesti/$slug': {
      id: '/povesti/$slug'
      path: '/$slug'
      fullPath: '/povesti/$slug'
      preLoaderRoute: typeof PovestiSlugRouteImport
      parentRoute: typeof PovestiRoute
    }
    '/producatori/': {
      id: '/producatori/'
      path: '/'
      fullPath: '/producatori/'
      preLoaderRoute: typeof ProducatoriIndexRouteImport
      parentRoute: typeof ProducatoriRoute
    }
    '/producatori/$id': {
      id: '/producatori/$id'
      path: '/$id'
      fullPath: '/producatori/$id'
      preLoaderRoute: typeof ProducatoriIdRouteImport
      parentRoute: typeof ProducatoriRoute
    }
    '/produse/': {
      id: '/produse/'
      path: '/'
      fullPath: '/produse/'
      preLoaderRoute: typeof ProduseIndexRouteImport
      parentRoute: typeof ProduseRoute
    }
    '/produse/$slug': {
      id: '/produse/$slug'
      path: '/$slug'
      fullPath: '/produse/$slug'
      preLoaderRoute: typeof ProduseSlugRouteImport
      parentRoute: typeof ProduseRoute
    }
    '/admin/produs/$id': {
      id: '/admin/produs/$id'
      path: '/produs/$id'
      fullPath: '/admin/produs/$id'
      preLoaderRoute: typeof AdminProdusIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminComenziRoute: typeof AdminComenziRoute
  AdminProducatoriRoute: typeof AdminProducatoriRoute
  AdminProduseRoute: typeof AdminProduseRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProdusIdRoute: typeof AdminProdusIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminComenziRoute: AdminComenziRoute,
  AdminProducatoriRoute: AdminProducatoriRoute,
  AdminProduseRoute: AdminProduseRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProdusIdRoute: AdminProdusIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PovestiRouteChildren {
  PovestiSlugRoute: typeof PovestiSlugRoute
  PovestiIndexRoute: typeof PovestiIndexRoute
}

const PovestiRouteChildren: PovestiRouteChildren = {
  PovestiSlugRoute: PovestiSlugRoute,
  PovestiIndexRoute: PovestiIndexRoute,
}

const PovestiRouteWithChildren =
  PovestiRoute._addFileChildren(PovestiRouteChildren)

interface ProducatoriRouteChildren {
  ProducatoriIdRoute: typeof ProducatoriIdRoute
  ProducatoriIndexRoute: typeof ProducatoriIndexRoute
}

const ProducatoriRouteChildren: ProducatoriRouteChildren = {
  ProducatoriIdRoute: ProducatoriIdRoute,
  ProducatoriIndexRoute: ProducatoriIndexRoute,
}

const ProducatoriRouteWithChildren = ProducatoriRoute._addFileChildren(
  ProducatoriRouteChildren,
)

interface ProduseRouteChildren {
  ProduseSlugRoute: typeof ProduseSlugRoute
  ProduseIndexRoute: typeof ProduseIndexRoute
}

const ProduseRouteChildren: ProduseRouteChildren = {
  ProduseSlugRoute: ProduseSlugRoute,
  ProduseIndexRoute: ProduseIndexRoute,
}

const ProduseRouteWithChildren =
  ProduseRoute._addFileChildren(ProduseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AplicatiaRoute: AplicatiaRoute,
  ComandaRoute: ComandaRoute,
  ContRoute: ContRoute,
  CosRoute: CosRoute,
  FavoriteRoute: FavoriteRoute,
  MesajeRoute: MesajeRoute,
  PovestiRoute: PovestiRouteWithChildren,
  ProducatoriRoute: ProducatoriRouteWithChildren,
  ProduseRoute: ProduseRouteWithChildren,
  SetariRoute: SetariRoute,
  TrimiteRoute: TrimiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
